[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  base = "."
  command = "yarn build"
  publish = "dist"
  # functions = "./functions"

[[context.production.plugins]]
  package = "./build/plugins/netlify-bump-version"