export const showExperience = true
export const showStrikes = false
export const showClouds = true
export const showMan = true
export const showParticles = true
export const manMaterial = 'vibrant' // glow | lambert | outline | vibrant
export const showTitles = true
export const showPortfolio = true
export const showCameraPath = false
export const showManAnimationLogs = false
export const showOrbitControls = false
export const composerEffect = 'vibrant' // neon | bloom | lambert | vibrant
